import { useEffect, useState, type ReactNode } from "react";
import { createRoot } from "react-dom/client";
import { Activity, AlertTriangle, ArrowLeftRight, BrainCircuit, CandlestickChart, ChevronRight, CircleDot, FlaskConical, LayoutDashboard, ListTree, Menu, Network, ScrollText, Settings, ShieldAlert, X, ZapOff } from "lucide-react";
import "./styles.css";

type Row = Record<string, unknown>;
type Page = "dashboard" | "markets" | "trades" | "strategies" | "evolution" | "memory" | "risk" | "logs" | "settings";
const list = (v: unknown): Row[] => Array.isArray(v) ? v as Row[] : [];
const text = (v: unknown): string => v === null || v === undefined || v === "" ? "n/a" : String(v);
const num = (v: unknown, n = 2): string => Number.isFinite(Number(v)) ? Number(v).toFixed(n) : "n/a";
const tone = (v: unknown): string => Number(v) > 0 ? "positive" : Number(v) < 0 ? "negative" : "muted";
const parse = (v: unknown, fallback: unknown): unknown => { try { return JSON.parse(String(v)); } catch { return fallback; } };

function useApi(path: string, interval = 5000) {
  const [data, setData] = useState<Row | Row[] | null>(null), [error, setError] = useState<string | null>(null), [loading, setLoading] = useState(true);
  const reload = async () => { try { const r = await fetch(path); if (!r.ok) throw new Error(`Request failed (${r.status})`); setData(await r.json() as Row | Row[]); setError(null); } catch (e) { setError(e instanceof Error ? e.message : "Connection unavailable"); } finally { setLoading(false); } };
  useEffect(() => {
    void reload();
    const id = window.setInterval(() => void reload(), interval);
    const protocol = window.location.protocol === "https:" ? "wss:" : "ws:";
    const socket = new WebSocket(`${protocol}//${window.location.host}/ws`);
    socket.addEventListener("message", () => void reload());
    return () => { window.clearInterval(id); socket.close(); };
  }, [path, interval]);
  return { data, error, loading, reload };
}
function Panel({ title, children, className = "" }: { title: string; children: ReactNode; className?: string }) { return <section className={`panel ${className}`}><h2>{title}</h2>{children}</section>; }
function State({ loading, error, empty, children }: { loading: boolean; error: string | null; empty: boolean; children: ReactNode }) { if (loading) return <p className="state">Loading current records.</p>; if (error) return <p className="state error"><AlertTriangle size={16}/>{error}. Check the local bot connection.</p>; return empty ? <p className="state">No records are available yet.</p> : <>{children}</>; }
function Badge({ children, state }: { children: ReactNode; state?: unknown }) { return <span className={`badge ${String(state ?? children).toLowerCase()}`}>{children}</span>; }
function Fact({ label, children }: { label: string; children: ReactNode }) { return <div className="fact"><span>{label}</span><b>{children}</b></div>; }
function Metric({ label, children, className = "" }: { label: string; children: ReactNode; className?: string }) { return <div className="metric"><span>{label}</span><strong className={className}>{children}</strong></div>; }
function Table({ rows, columns }: { rows: Row[]; columns: Array<[string, (r: Row) => ReactNode]> }) { return <div className="table-wrap"><table><thead><tr>{columns.map(([name]) => <th key={name}>{name}</th>)}</tr></thead><tbody>{rows.map((r, i) => <tr key={text(r.trade_id ?? r.lesson_id ?? r.id ?? i)}>{columns.map(([name, cell]) => <td key={name}>{cell(r)}</td>)}</tr>)}</tbody></table></div>; }
function Heading({ title, description }: { title: string; description: string }) { return <header className="page-heading"><h1>{title}</h1><p>{description}</p></header>; }
function Chart({ candles, markers = {} }: { candles: Row[]; markers?: Row }) { if (candles.length < 2) return <p className="state">Waiting for confirmed candles.</p>; const w = 760, h = 240, vals = candles.flatMap(c => [Number(c.h), Number(c.l)]).filter(Number.isFinite), lo = Math.min(...vals), hi = Math.max(...vals), y = (p: number) => h - 18 - ((p - lo) / Math.max(1, hi - lo)) * (h - 34), step = w / candles.length; return <svg className="chart" viewBox={`0 0 ${w} ${h}`} role="img" aria-label="Confirmed market candles with persisted trade markers">{candles.map((c, i) => { const up = Number(c.c) >= Number(c.o), x = i * step + step / 2; return <g key={text(c.ts)} className={up ? "up" : "down"}><line x1={x} x2={x} y1={y(Number(c.h))} y2={y(Number(c.l))}/><rect x={x - Math.max(1, step * .28)} y={y(Math.max(Number(c.o), Number(c.c)))} width={Math.max(2, step * .55)} height={Math.max(1, Math.abs(y(Number(c.o)) - y(Number(c.c))))}/></g>; })}{[["entry_px", "ENTRY", "entry"], ["stop_px", "STOP", "stop"], ["take_profit_px", "TARGET", "target"], ["exit_px", "EXIT", "exit"]].map(([key, label, cls]) => Number.isFinite(Number(markers[key])) ? <g key={key} className={`marker ${cls}`}><line x1="0" x2={w} y1={y(Number(markers[key]))} y2={y(Number(markers[key]))}/><text x="8" y={y(Number(markers[key])) - 4}>{label}</text></g> : null)}</svg>; }

function Dashboard() { const status = useApi("/api/status"), candle = useApi("/api/candles?limit=90"), s = !Array.isArray(status.data) ? status.data : null; if (!s) return <div className="page"><State loading={status.loading} error={status.error} empty={false}><></></State></div>; const daily = (s.daily ?? {}) as Row, total = (s.totals ?? {}) as Row, pos = list(s.openPositions)[0] ?? null, dec = s.latestDecision as Row | null, verdict = parse(dec?.risk_verdict, {}) as Row; return <div className="page"><div className={`risk-strip ${s.killReason || s.emergencyHalted ? "halted" : ""}`}><ShieldAlert size={18}/>{s.killReason || s.emergencyHalted ? `Risk halt: ${text(s.killReason)}` : "Risk controls gate every new entry."}</div><div className="metric-row"><Metric label="Demo equity">{num(s.equity)} USDT</Metric><Metric label="Daily loss" className={Number(daily.lossPct) > 0 ? "negative" : ""}>{num(daily.lossPct)}%</Metric><Metric label="Drawdown" className={Number(s.drawdownPct) > 0 ? "negative" : ""}>{num(s.drawdownPct)}%</Metric><Metric label="Closed trades">{text(total.closed)}</Metric><Metric label="Expectancy" className={tone(total.expectancyR)}>{num(total.expectancyR)}R</Metric></div><div className="dashboard-grid"><Panel title="Market path"><State loading={candle.loading} error={candle.error} empty={list(candle.data).length < 2}><Chart candles={list(candle.data)} markers={pos ?? {}}/></State></Panel><Panel title="Current position">{pos ? <><Badge state={pos.side}>{text(pos.side)}</Badge><Fact label="Instrument">{text(pos.instrument)}</Fact><Fact label="Entry / mark">{num(pos.entry_px, 1)} / {num(pos.mark_px, 1)}</Fact><Fact label="Unrealized PnL"><span className={tone(pos.upl)}>{num(pos.upl)} USDT</span></Fact><Fact label="Stop / target">{num(pos.stop_px, 1)} / {num(pos.take_profit_px, 1)}</Fact></> : <><p className="state">No open position.</p><Fact label="Latest action">{text(dec?.decision)}</Fact></>}</Panel></div><div className="dashboard-grid lower"><Panel title="Latest decision trace">{dec ? <><Metric label="AI decision" className={String(dec.decision) === "LONG" ? "positive" : String(dec.decision) === "SHORT" ? "negative" : ""}>{text(dec.decision)}</Metric><Fact label="Strategy">{text(dec.strategy)}</Fact><Fact label="Regime">{text(dec.regime)}</Fact><Fact label="Raw / calibrated">{num(dec.raw_confidence)} / {num(dec.calibrated_confidence)}</Fact><Fact label="Risk engine"><Badge state={verdict.reason}>{text(verdict.reason)}</Badge></Fact></> : <p className="state">No decision has been recorded yet.</p>}</Panel><Panel title="Operating limits"><Fact label="Risk per trade">{text((s.limits as Row)?.risk_per_trade_pct)}%</Fact><Fact label="Max leverage">{text((s.limits as Row)?.max_leverage)}x</Fact><Fact label="Max positions">{text((s.limits as Row)?.max_concurrent_positions)}</Fact><Fact label="Environment">DEMO only</Fact></Panel></div></div>; }
function Markets() { const api = useApi("/api/market"), d = !Array.isArray(api.data) ? api.data : null, snap = d?.snapshot as Row | null, weights = d?.weights as Row | null; return <div className="page"><Heading title="Markets" description="Current inputs and weighted signals before an entry decision."/><State loading={api.loading} error={api.error} empty={!d}><div className="dashboard-grid"><Panel title="Feature snapshot">{snap ? <><Fact label="Price">{num(snap.price, 2)}</Fact><Fact label="EMA20 / EMA50">{num(snap.ema20)} / {num(snap.ema50)}</Fact><Fact label="RSI / ADX">{num(snap.rsi14, 1)} / {num(snap.adx14, 1)}</Fact><Fact label="ATR %">{num(snap.atrPct, 2)}%</Fact><Fact label="Volume ratio">{num(snap.volumeRatio)}</Fact><Fact label="Regime">{text(d?.regime)}</Fact></> : <p className="state">Waiting for a confirmed market snapshot.</p>}</Panel><Panel title="Signal weights">{weights ? Object.entries(weights).map(([k, v]) => <Fact key={k} label={k}>{num(v)}</Fact>) : <p className="state">No learning weights recorded.</p>}</Panel></div><Panel title="Watchlist scanner"><Table rows={list(d?.scan)} columns={[["Instrument", r => text(r.instrument)], ["Regime", r => <Badge state={r.regime}>{text(r.regime)}</Badge>], ["Price", r => num(r.price, 2)], ["Signal", r => <span className={tone(r.score)}>{num(r.score)}</span>], ["Strategy", r => text(r.strategy)], ["Tradable", r => r.tradable ? "Yes" : "No"]]}/></Panel></State></div>; }
function Trades() { const api = useApi("/api/trades"), [query, setQuery] = useState(""), [id, setId] = useState<string | null>(null), detail = useApi(id ? `/api/trades/${encodeURIComponent(id)}` : "/api/trades/__none__", 15000); const data = list(api.data).filter(r => `${text(r.trade_id)} ${text(r.side)} ${text(r.strategy)} ${text(r.regime)}`.toLowerCase().includes(query.toLowerCase())), d = !Array.isArray(detail.data) ? detail.data : null, trade = d?.trade as Row | null; return <div className="page"><Heading title="Trades" description="Select a trade to inspect decision, execution, review, and replay."/><label className="search">Filter trades<input value={query} onChange={e => setQuery(e.target.value)} placeholder="ID, side, strategy, regime"/></label><Panel title="Trade ledger"><State loading={api.loading} error={api.error} empty={!data.length}><Table rows={data} columns={[["Trade", r => <button className="row-button" onClick={() => setId(text(r.trade_id))}>{text(r.trade_id)}</button>], ["Side", r => <Badge state={r.side}>{text(r.side)}</Badge>], ["Strategy", r => `${text(r.strategy)} V${text(r.strategy_version)}`], ["R", r => <span className={tone(r.result_r ?? r.live_r)}>{num(r.result_r ?? r.live_r)}</span>], ["PnL", r => <span className={tone(r.pnl ?? r.upl)}>{num(r.pnl ?? r.upl)} USDT</span>], ["State", r => <Badge state={r.status}>{text(r.status)}</Badge>]]}/></State></Panel>{id ? <section className="drawer"><button className="close" onClick={() => setId(null)} aria-label="Close trade detail"><X/></button><State loading={detail.loading} error={detail.error} empty={!d}><>{trade ? <><h2>{text(trade.trade_id)}</h2><Chart candles={list(d?.candles)} markers={trade}/><div className="dashboard-grid lower"><Panel title="Execution"><Fact label="Orders">{list(d?.orders).length}</Fact><Fact label="Fills">{list(d?.fills).length}</Fact><Fact label="Exit">{text(trade.exit_reason)}</Fact><Fact label="Result">{num(trade.result_r)}R</Fact></Panel><Panel title="Post-trade review"><pre>{JSON.stringify(d?.review ?? "No review recorded.", null, 2)}</pre></Panel></div></> : null}</></State></section> : null}</div>; }
function Strategies() { const api = useApi("/api/strategies"), d = !Array.isArray(api.data) ? api.data : null; return <div className="page"><Heading title="Strategies" description="Immutable versions and their evaluation state."/><Panel title="Version registry"><State loading={api.loading} error={api.error} empty={!list(d?.strategies).length}><Table rows={list(d?.strategies)} columns={[["Strategy", r => text(r.name)], ["Version", r => `V${text(r.version)}`], ["Status", r => <Badge state={r.status}>{text(r.status)}</Badge>], ["Parent", r => r.parent_version ? `V${text(r.parent_version)}` : "Base"], ["Hypothesis", r => text(r.hypothesis)]]}/></State></Panel></div>; }
function Evolution() { const api = useApi("/api/evolution"), d = !Array.isArray(api.data) ? api.data : null; return <div className="page"><Heading title="Evolution" description="Evidence controls promotion, the agent cannot promote itself."/><Panel title="Version timeline"><State loading={api.loading} error={api.error} empty={!list(d?.strategies).length}><Table rows={list(d?.strategies)} columns={[["Candidate", r => `${text(r.name)} V${text(r.version)}`], ["State", r => <Badge state={r.status}>{text(r.status)}</Badge>], ["Parent", r => text(r.parent_version)], ["Hypothesis", r => text(r.hypothesis)], ["Parameters", r => text(r.params)]]}/></State></Panel><Panel title="Champion comparison"><State loading={api.loading} error={api.error} empty={!list(d?.comparisons).length}><Table rows={list(d?.comparisons)} columns={[["Champion", r => text(r.champion)], ["Challenger", r => text(r.challenger)], ["Result", r => <Badge state={Number(r.promoted) ? "approved" : "rejected"}>{Number(r.promoted) ? "PROMOTED" : "NOT PROMOTED"}</Badge>], ["Reasons", r => list(parse(r.reasons, [])).map(text).join("; ")]]}/></State></Panel><Panel title="Promotion evidence"><EventTable events={list(d?.events)}/></Panel></div>; }
function Memory() { const lessons = useApi("/api/lessons"), strategy = useApi("/api/strategies"), [tab, setTab] = useState("Lessons"), s = !Array.isArray(strategy.data) ? strategy.data : null; return <div className="page"><Heading title="Memory" description="Learning remains evidence-bound until observations support it."/><div className="tabs">{["Lessons", "Regimes", "Signals", "Confidence"].map(x => <button key={x} className={tab === x ? "active" : ""} onClick={() => setTab(x)}>{x}</button>)}</div>{tab === "Lessons" ? <Panel title="Lessons"><State loading={lessons.loading} error={lessons.error} empty={!list(lessons.data).length}><Table rows={list(lessons.data)} columns={[["Lesson", r => text(r.statement)], ["Status", r => <Badge state={r.status}>{text(r.status)}</Badge>], ["Scope", r => `${text(r.scope_strategy)} / ${text(r.scope_regime)}`], ["Win / loss", r => `${text(r.wins)} / ${text(r.losses)}`], ["Expectancy", r => `${num(r.expectancy_r)}R`], ["Confidence", r => `${num(Number(r.confidence) * 100, 0)}%`]]}/></State></Panel> : <Panel title={tab}>{tab === "Regimes" ? <pre>{JSON.stringify(s?.regimeMatrix ?? "No regime evidence recorded.", null, 2)}</pre> : tab === "Signals" ? <pre>{JSON.stringify(s?.weights ?? "No weight evidence recorded.", null, 2)}</pre> : s?.calibration ? <pre>{JSON.stringify((s.calibration as Row).buckets, null, 2)}</pre> : <p className="state">Not enough closed trades to calibrate confidence.</p>}</Panel>}</div>; }
function EventTable({ events }: { events: Row[] }) { return <Table rows={events} columns={[["Time", r => text(r.ts).replace("T", " ").slice(0, 19)], ["Kind", r => <Badge state={r.kind}>{text(r.kind)}</Badge>], ["Detail", r => text(r.payload)]]}/>; }
function Risk() { const status = useApi("/api/status"), events = useApi("/api/events"), s = !Array.isArray(status.data) ? status.data : null; return <div className="page"><Heading title="Risk" description="Hard limits remain outside AI and evolution control."/><div className="dashboard-grid"><Panel title="Risk state"><State loading={status.loading} error={status.error} empty={!s}><Fact label="Bot state"><Badge state={s?.botState}>{text(s?.botState)}</Badge></Fact><Fact label="Drawdown">{num(s?.drawdownPct)}%</Fact><Fact label="Daily loss">{num((s?.daily as Row)?.lossPct)}%</Fact><Fact label="Available equity">{num(s?.equity)} USDT</Fact></State></Panel><Panel title="Hard limits">{s ? Object.entries(s.limits as Row).map(([k, v]) => <Fact key={k} label={k}>{text(v)}</Fact>) : null}</Panel></div><Panel title="Risk event timeline"><EventTable events={list(events.data).filter(e => String(e.kind).includes("RISK") || String(e.kind) === "STATE")}/></Panel></div>; }
function Logs() { const api = useApi("/api/events"), [filter, setFilter] = useState("ALL"), [query, setQuery] = useState(""), events = list(api.data).filter(e => (filter === "ALL" || String(e.kind).includes(filter)) && JSON.stringify(e).toLowerCase().includes(query.toLowerCase())); const exportEvents = () => { const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([JSON.stringify(events, null, 2)], { type: "application/json" })); link.download = "evoquant-events.json"; link.click(); URL.revokeObjectURL(link.href); }; return <div className="page"><Heading title="Logs" description="Stored events are redacted before exposure to this console."/><div className="tabs">{["ALL", "RISK", "TRADE", "ERROR", "PROMOTION"].map(x => <button key={x} className={filter === x ? "active" : ""} onClick={() => setFilter(x)}>{x}</button>)}<button onClick={exportEvents} disabled={!events.length}>Export filtered logs</button></div><label className="search">Search logs<input value={query} onChange={e => setQuery(e.target.value)} placeholder="Event kind, detail, identifier"/></label><Panel title="System events"><State loading={api.loading} error={api.error} empty={!events.length}><EventTable events={events}/></State></Panel></div>; }
function SettingsPage() { const api = useApi("/api/settings", 15000), s = !Array.isArray(api.data) ? api.data : null; return <div className="page"><Heading title="Settings" description="Demo environment and hard risk controls are visibly locked."/><State loading={api.loading} error={api.error} empty={!s}><div className="dashboard-grid"><Panel title="Exchange"><Fact label="Exchange">{text((s?.exchange as Row)?.exchange)}</Fact><Fact label="Environment"><Badge state="okx-demo">{text((s?.exchange as Row)?.environment)}</Badge></Fact><Fact label="Policy">{text((s?.exchange as Row)?.note)}</Fact></Panel><Panel title="AI provider"><Fact label="Provider">{text((s?.llm as Row)?.provider)}</Fact><Fact label="Model">{text((s?.llm as Row)?.model)}</Fact><Fact label="API key">{text((s?.llm as Row)?.apiKeyMasked)}</Fact></Panel></div><Panel title="Learning and evolution"><pre>{JSON.stringify(s?.learning ?? {}, null, 2)}</pre></Panel></State></div>; }

const nav: Array<[Page, string, typeof LayoutDashboard]> = [["dashboard", "Dashboard", LayoutDashboard], ["markets", "Markets", CandlestickChart], ["trades", "Trades", ArrowLeftRight], ["strategies", "Strategies", ListTree], ["evolution", "Evolution", FlaskConical], ["memory", "Memory", BrainCircuit], ["risk", "Risk", ShieldAlert], ["logs", "Logs", ScrollText], ["settings", "Settings", Settings]];
function App() { const [page, setPage] = useState<Page>("dashboard"), [menu, setMenu] = useState(false), [notice, setNotice] = useState<string | null>(null), [busy, setBusy] = useState(false), status = useApi("/api/status"), s = !Array.isArray(status.data) ? status.data : null; const control = async (path: string, prompt?: string) => { if (prompt && !window.confirm(prompt)) return; setBusy(true); try { const r = await fetch(path, { method: "POST" }); if (!r.ok) throw new Error(`Request failed (${r.status})`); setNotice(path.endsWith("pause") ? "Bot paused." : "Emergency stop activated."); await status.reload(); } catch (e) { setNotice(e instanceof Error ? e.message : "Control request failed."); } finally { setBusy(false); } }; const content: Record<Page, ReactNode> = { dashboard: <Dashboard/>, markets: <Markets/>, trades: <Trades/>, strategies: <Strategies/>, evolution: <Evolution/>, memory: <Memory/>, risk: <Risk/>, logs: <Logs/>, settings: <SettingsPage/> }; return <div className="shell"><aside className={menu ? "sidebar open" : "sidebar"}><div className="brand"><Activity size={21}/><span>EvoQuant</span><button className="mobile-icon" onClick={() => setMenu(false)} aria-label="Close navigation"><X/></button></div><nav aria-label="Primary navigation">{nav.map(([id, label, Icon]) => <button key={id} className={page === id ? "active" : ""} onClick={() => { setPage(id); setMenu(false); }}><Icon size={18}/><span>{label}</span><ChevronRight size={14}/></button>)}</nav><div className="sidebar-note"><CircleDot size={14}/>Simulated trading only</div></aside><main><header className="topbar"><button className="mobile-icon" onClick={() => setMenu(true)} aria-label="Open navigation"><Menu/></button><div className="top-meta"><Badge state="okx-demo">OKX DEMO</Badge><span>{text(s?.instrument)}</span><span>{text(s?.timeframe)}</span><span className={status.error ? "negative" : "connection"}><Network size={14}/>{status.error ? "Disconnected" : s ? "Connected" : "Connecting"}</span></div><div className="controls"><Badge state={s?.botState}>{text(s?.botState)}</Badge><button disabled={busy} onClick={() => void control("/api/pause")}>Pause bot</button><button disabled={busy} className="danger" onClick={() => void control("/api/emergency-stop", "Disable new entries and cancel pending entries?")}><ZapOff size={16}/>Emergency stop</button></div></header>{notice ? <div className="notice" role="status">{notice}<button onClick={() => setNotice(null)} aria-label="Dismiss notice"><X size={16}/></button></div> : null}{content[page]}</main></div>; }
createRoot(document.getElementById("root")!).render(<App/>);
